version: '3'

services:
  service-a:
    restart: always
    container_name: cep-validator
    build:
      context: ./service_a
      dockerfile: Dockerfile
    entrypoint: ["cep-validator"]
    ports:
      - "8080:8080"

  service-b:
    restart: always
    container_name: temperatura-cep
    build:
      context: ./service_b
      dockerfile: Dockerfile
    entrypoint: ["temperatura-cep"]
    ports:
      - "8081:8081"
    
  collector:
    restart: always
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  zipkin:
    restart: always
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
