version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics

  service-a:
    container_name: cep-validator
    build:
      context: .
    environment:
      - EXTERNAL_CALL_URL=http://serviceb:8081
      - EXTERNAL_CALL_METHOD=GET
      - OTEL_SERVICE_NAME=service-a
      - OTEL_EXPORT_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
    entrypoint: ["cep-validator"]
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  service-b:
    container_name: temperatura-cep
    build:
      context: .
    environment:
      - OTEL_SERVICE_NAME=service-b
      - OTEL_EXPORT_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8081
    entrypoint: ["temperatura-cep"]
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector
